# -*- coding: utf-8 -*-
"""distancia.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yzuKzoOw7PIkOsSGHP9ZUNEbpXth-xTW
"""

import geopandas as gpd
from shapely.geometry import Point
import pandas as pd

"""## Coordenadas de la Universidad Distrital"""

ud_lon, ud_lat = -74.0688, 4.6301

"""# se crea un punto con las coordenadas

"""

ud_point = Point(ud_lon, ud_lat)
ud_point

"""# se crea un GeoDataFrame con el punto de la Universidad
creo un dataframe y lo llamo ud_gdf el cual contiene la geometría del punto ud_point que es la ubicación de la Universidad
"""

ud_gdf = gpd.GeoDataFrame({'geometry': [ud_point]}, crs='epsg:4326')

"""se pasa el sistema de ud_gdf al sistema de coordenadas de referencia CRS EPSG:9377"""

ud_gdf = ud_gdf.to_crs('epsg:9377')

"""aqui llamo o leo el dataframe de las localidades

"""

gdf_localidades = gpd.read_file("localidades.json")
gdf_localidades

"""aqui paso la carpeta de localidades a proyeccion 9377"""

gdf_localidades.to_crs(epsg=9377, inplace=True)

"""creo el centro de las localidades"""

gdf_localidades["centroide"]=gdf_localidades.centroid
gdf_localidades

"""calculo la distancia desde el centroide de las localidades a la coordenada de la universidad"""

gdf_localidades['distancia_ud'] = gdf_localidades['centroide'].apply(lambda geom: ud_gdf.geometry.values[0].distance(geom))
gdf_localidades

"""aqui paso de metros a kilometros y los ordeno de menor a mayor
ademas poner solo las colunmas que me interesan
"""

gdf_localidades['distancia_ud_km'] = gdf_localidades['distancia_ud'] / 1000
localidades_ordenadas = gdf_localidades.sort_values(by='distancia_ud_km')
localidades_ordenadas[['LocNombre', 'distancia_ud_km']]