# -*- coding: utf-8 -*-
"""introgeopandas-2024/04/29.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1e2Yr262DXWSAE8StubrS5tSbvkv9n41b
"""

import geopandas as gpd

"""#fuentes de datos espaciales
las que nosotros creamos
repositorios externos: infraestructura de Datos espaciales (ejemplo: ideca)
"""

gdf_localidades = gpd.read_file("localidades.json")

gdf_localidades.crs

gdf_localidades.to_crs(epsg=9377, inplace=True)

gdf_localidades["area"]=gdf_localidades.area/1000000

gdf_localidades

gdf_localidades["centroide"]=gdf_localidades.centroid

gdf_localidades

"""#calcular la distancia de la universidad a cada localidad
crear un punto de la localizacion de la universidad distrital(recordar el crs)
#utilizar la biblioteca shapely

si es necesario, covertir el crs original al 9733
calcular la longitud o la distancia entre el punto de la ud y cada centroide de mi geodataframe

ir a maps y se busca a la universidad distrital y se busca el centroide
crs? usa gogle map
9377

# distancia desde un punto a las geometrias del geodataset desde el centroide de las localidades hasta la universidad
"""

from shapely.geometry import Point
import geopandas as gpd

"""creacion de un punto"""

#point(longitud, latitud)
universidad = Point(-74.06659808643116, 4.628283807240232)
universidad

universidad= gpd.GeoSeries(universidad, crs=4326)
universidad

universidades=universidad.to_crs(epsg=9377)
universidades

"""#tomar la distancia de la universidad distrital a cada uno de las localidades del centroide"""

gdf_localidades["distancia"]=[float(universidad.distance(centroide))/1000 for centroide in gdf_localidades.centroide]
gdf_localidades["distancia"]

gdf_localidades.plot()

# agregar capas
mape=gdf_localidades.plot(figsize=(10,10))
gdf_localidades["centroide"].plot(ax=mape, color="white")

#importar contextyle

mapa_2=gdf_localidades.plot(
    column="LocNombre",
    figsize=(15,15),
    edgecolor="black",
    cmap="tab20",
    legend=True,
    legend_kwds= {
        "loc" : "upper left"
    }

)

"""craer un mapa coropletico donde vivo y los barrios"""